all:

paraldc: paraldc.cpp
	g++ -Wall -o paraldc paraldc.cpp
read-bin: read-bin.cpp
	g++ -Wall -o read-bin read-bin.cpp

write-bin: write-bin.cpp
	g++ -Wall -o write-bin write-bin.cpp

mywc: mywc.cpp
	g++ -Wall -o mywc mywc.cpp

clean:
	rm -f test.txt *.o read-bin write-bin mywc paraldc
